### ISSUE TITLE
Missing types with custom class deserializers

### ISSUE THREAD

**Issue by mauvealerts** [yukinarit/pyserde#167]
The code generation doesn't put `Optional` or `Union` in scope when calling a custom class deserializer. This results in a `NameError` during deserialization.

Example
```py
from dataclasses import dataclass
from typing import Optional

from serde import deserialize, from_dict


def deserialize_maybe_str(_typ, value):
    return value


@deserialize(deserializer=deserialize_maybe_str)
@dataclass
class CustomDe:
    maybe_str: Optional[str]


if __name__ == "__main__":
    data = {"maybe_str": "bye"}
    print(f"from_dict({data}) = {from_dict(CustomDe, data)}")
```
Output
```
Traceback (most recent call last):
  File "C:\Users\mauve\dev\modlunky2\src\union_demo.py", line 19, in <module>
    print(f"from_dict({data}) = {from_dict(CustomDe, data)}")
  File "C:\Users\mauve\dev\modlunky2\.venv\lib\site-packages\serde\de.py", line 319, in from_dict
    return from_obj(cls, o, named=True, reuse_instances=reuse_instances)
  File "C:\Users\mauve\dev\modlunky2\.venv\lib\site-packages\serde\de.py", line 253, in from_obj
    return serde_scope.funcs[FROM_DICT](o, reuse_instances=reuse_instances)
  File "<string>", line 10, in from_dict
NameError: name 'Optional' is not defined
```

**Comment by yukinarit** [comment]
Thanks for reporting! Will take a look!

**Comment by yukinarit** [comment]
hmm I got the different error 🤔 

```python
Traceback (most recent call last):
  File "/Users/yukinari/repos/pyserde/examples/a.py", line 13, in <module>
    class CustomDe:
  File "/Users/yukinari/Library/Caches/pypoetry/virtualenvs/pyserde-examples-eLlM1BJJ-py3.9/lib/python3.9/site-packages/serde/de.py", line 196, in wrap
    add_func(scope, FROM_ITER, render_from_iter(cls, deserializer), g)
  File "/Users/yukinari/Library/Caches/pypoetry/virtualenvs/pyserde-examples-eLlM1BJJ-py3.9/lib/python3.9/site-packages/serde/de.py", line 689, in render_from_iter
    return env.get_template('iter').render(func=FROM_ITER, serde_scope=getattr(cls, SERDE_SCOPE), fields=defields(cls))
  File "/Users/yukinari/Library/Caches/pypoetry/virtualenvs/pyserde-examples-eLlM1BJJ-py3.9/lib/python3.9/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/Users/yukinari/Library/Caches/pypoetry/virtualenvs/pyserde-examples-eLlM1BJJ-py3.9/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 16, in top-level template code
  File "/Users/yukinari/Library/Caches/pypoetry/virtualenvs/pyserde-examples-eLlM1BJJ-py3.9/lib/python3.9/site-packages/serde/de.py", line 479, in render
    f'serde_custom_class_deserializer({arg.type.__name__}, {arg.datavar}, {arg.data}, '
  File "/opt/homebrew/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/typing.py", line 701, in __getattr__
    raise AttributeError(attr)
AttributeError: __name__
```

**Comment by mauvealerts** [comment]
Interesting. The output in my original-comment is from a Python 3.10 venv. Notably, I can use `serde.inspect` on it.

With a Python 3.9 venv, I get the exact same error you do. Since it fails sooner, `serde.inspect` doesn't work, of course.

**Comment by yukinarit** [comment]
OK, it reproduced with a small fix.

**Comment by yukinarit** [comment]
@mauvealerts 

I think #169 fixed the issue. Could you please verify?

**Comment by mauvealerts** [comment]
Yes, it now works for me. Thanks!

**Comment by yukinarit** [comment]
Great! Thanks!
