### ISSUE TITLE
Support typing.Literal as a type

### ISSUE THREAD

**Issue by kmsquire** [yukinarit/pyserde#220]
The following leads to an error, but it should(?) be possible to check this:

```python
from typing import Literal
from serde import serde
from serde.json import from_json, to_json

@serde
class Foo:
    x: Literal["a","b"]
```

Running this currently gives:
```python
$ python literal_test.py
Traceback (most recent call last):
  File "/Users/kevin.squire/tmp/pyserde/literal_test.py", line 6, in <module>
    class Foo:
  File "/Users/kevin.squire/tmp/pyserde/serde/__init__.py", line 62, in serde
    return wrap(_cls)
  File "/Users/kevin.squire/tmp/pyserde/serde/__init__.py", line 55, in wrap
    serialize(cls, **kwargs)
  File "/Users/kevin.squire/tmp/pyserde/serde/se.py", line 245, in serialize
    return wrap(_cls)
  File "/Users/kevin.squire/tmp/pyserde/serde/se.py", line 220, in wrap
    g[typename(typ)] = typ
  File "/Users/kevin.squire/tmp/pyserde/serde/compat.py", line 138, in typename
    return typ.__name__
  File "/Users/kevin.squire/.pyenv/versions/3.9.11/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/typing.py", line 711, in __getattr__
    raise AttributeError(attr)
AttributeError: __name__
```

**Comment by kmsquire** [comment]
Note that the above error appears for Python 3.9 (and probably earlier).  On Python 3.10, `typ.__name__` is set for `Literal`.  

That said, the following still errors on Python 3.10:

```python
from typing import Literal
from serde import serde
from serde.json import from_json, to_json

@serde
class Foo:
    x: Literal["a","b"]

f = Foo("a")
to_json(f)
```

which gives

```python
Traceback (most recent call last):
  File "/Users/kevin.squire/tmp/pyserde/serde/se.py", line 275, in to_obj
    return serde_scope.funcs[TO_DICT](o, reuse_instances=reuse_instances, convert_sets=convert_sets)
  File "<string>", line 13, in to_dict
  File "/Users/kevin.squire/tmp/pyserde/serde/core.py", line 160, in raise_unsupported_type
    raise SerdeError(f"Unsupported type: {typename(type(obj))}")
serde.compat.SerdeError: Unsupported type: str

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kevin.squire/tmp/pyserde/literal_test.py", line 11, in <module>
    to_json(f)
  File "/Users/kevin.squire/tmp/pyserde/serde/json.py", line 38, in to_json
    return se.serialize(to_dict(obj, reuse_instances=False, convert_sets=True), **opts)
  File "/Users/kevin.squire/tmp/pyserde/serde/se.py", line 359, in to_dict
    return to_obj(o, named=True, reuse_instances=reuse_instances, convert_sets=convert_sets)
  File "/Users/kevin.squire/tmp/pyserde/serde/se.py", line 299, in to_obj
    raise SerdeError(e)
serde.compat.SerdeError: Unsupported type: str
```
