### ISSUE TITLE
Variable length tuples throw exception

### ISSUE THREAD

**Issue by AustinScola** [yukinarit/pyserde#231]
I think there is a bug with tuples of variable lengths:

## Example
```python
from serde.de import deserialize
from serde.json import from_json


@deserialize
class Foo:
    values: tuple[int, ...]

foo = from_json(Foo, '{"values": [1, 2, 3]}')
```

## Stacktrace
```
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/private/tmp/tuple.py", line 6, in <module>
    class Foo:
  File "/usr/local/lib/python3.9/site-packages/serde/de.py", line 263, in deserialize
    return wrap(_cls)
  File "/usr/local/lib/python3.9/site-packages/serde/de.py", line 229, in wrap
    g[typename(typ)] = typ
  File "/usr/local/lib/python3.9/site-packages/serde/compat.py", line 165, in typename
    return typ.__name__
AttributeError: 'ellipsis' object has no attribute '__name__'
```

**Comment by yukinarit** [comment]
Not supported yet 🙂

**Comment by yukinarit** [comment]
Supported in pyserde v0.9.4
