### ISSUE TITLE
Numpy v1.23.0 breaks pyserde compatability in Python versions <= 3.8

### ISSUE THREAD

**Issue by skogsvik** [yukinarit/pyserde#246]
The commit https://github.com/numpy/numpy/commit/7739583f5fb39c31e83010a3153fa078004e55eb splits the typing library into a public and private part.

A consequence is that pyserde's compatibility mode for Python 3.8 (and below) which relies on some private types will no longer work as those types have now moved.

**Comment by skogsvik** [comment]
Adding an MRE

Installing with `pipenv install` and running with `pipenv run python mre.py` yields the following error:
```
> pipenv run python mre.py
Traceback (most recent call last):
  File "C:\Users\[REDACTED]\.virtualenvs\mre-rZZzZDh8\lib\site-packages\serde\compat.py", line 197, in type_args
    args = typ.__args__  # type: ignore
AttributeError: type object 'int' has no attribute '__args__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\[REDACTED]\.virtualenvs\mre-rZZzZDh8\lib\site-packages\serde\compat.py", line 92, in get_args
    return typing.get_args(typ) or get_np_args(typ)  # python>=3.8 typing module has get_args.
  File "C:\Users\[REDACTED]\.virtualenvs\mre-rZZzZDh8\lib\site-packages\serde\compat.py", line 29, in get_np_args
    if isinstance(tp, npt._generic_alias._GenericAlias) and tp.__origin__ is not ClassVar:
AttributeError: module 'numpy.typing' has no attribute '_generic_alias'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mre.py", line 4, in <module>
    class Example:
  File "C:\Users\[REDACTED]\.virtualenvs\mre-rZZzZDh8\lib\site-packages\serde\__init__.py", line 114, in serde
    return wrap(_cls)
  File "C:\Users\[REDACTED]\.virtualenvs\mre-rZZzZDh8\lib\site-packages\serde\__init__.py", line 107, in wrap
    serialize(cls, **kwargs)
  File "C:\Users\[REDACTED]\.virtualenvs\mre-rZZzZDh8\lib\site-packages\serde\se.py", line 255, in serialize
    return wrap(_cls)
  File "C:\Users\[REDACTED]\.virtualenvs\mre-rZZzZDh8\lib\site-packages\serde\se.py", line 227, in wrap
    for typ in iter_types(cls):
  File "C:\Users\[REDACTED]\.virtualenvs\mre-rZZzZDh8\lib\site-packages\serde\compat.py", line 263, in iter_types
    yield from iter_types(f.type)
  File "C:\Users\[REDACTED]\.virtualenvs\mre-rZZzZDh8\lib\site-packages\serde\compat.py", line 266, in iter_types
    elif is_opt(cls):
  File "C:\Users\[REDACTED]\.virtualenvs\mre-rZZzZDh8\lib\site-packages\serde\compat.py", line 402, in is_opt
    args = type_args(typ)
  File "C:\Users\[REDACTED]\.virtualenvs\mre-rZZzZDh8\lib\site-packages\serde\compat.py", line 203, in type_args
    return get_args(typ)
  File "C:\Users\[REDACTED]\.virtualenvs\mre-rZZzZDh8\lib\site-packages\serde\compat.py", line 94, in get_args
    return typing_inspect.get_args(typ) or get_np_args(typ)
  File "C:\Users\[REDACTED]\.virtualenvs\mre-rZZzZDh8\lib\site-packages\serde\compat.py", line 29, in get_np_args
    if isinstance(tp, npt._generic_alias._GenericAlias) and tp.__origin__ is not ClassVar:
AttributeError: module 'numpy.typing' has no attribute '_generic_alias'
```

Downgrading to `numpy = "<1.23.0"` solves the issue.

### mre.py
```python
import serde

@serde.serde
class Example:
    a: int

```

### pipfile
```pipfile
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
pyserde = ">=0.7.3"
numpy = ">=1.23"

[dev-packages]

[requires]
python_version = "3.8"
```

### pipfile.lock
```json
{
    "_meta": {
        "hash": {
            "sha256": "23528fb50b64570f01ab2c391fce68d876db37f2b58c4969f2dea31cd5479071"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.8"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "casefy": {
            "hashes": [
                "sha256:141f5da31b3506adbe5b3071bd3c49312be89d1e5e8ed024c5b6657e9bba767e",
                "sha256:38a10846bf1b856c9df4cc411d13735d2b688f335e7714cc8dd4b5d8483a52dd"
            ],
            "markers": "python_version >= '3.6'",
            "version": "==0.1.2"
        },
        "jinja2": {
            "hashes": [
                "sha256:31351a702a408a9e7595a8fc6150fc3f43bb6bf7e319770cbc0db9df9437e852",
                "sha256:6088930bfe239f0e6710546ab9c19c9ef35e29792895fed6e6e31a023a182a61"
            ],
            "markers": "python_full_version >= '3.7.0'",
            "version": "==3.1.2"
        },
        "markupsafe": {
            "hashes": [
                "sha256:0212a68688482dc52b2d45013df70d169f542b7394fc744c02a57374a4207003",
                "sha256:089cf3dbf0cd6c100f02945abeb18484bd1ee57a079aefd52cffd17fba910b88",
                "sha256:10c1bfff05d95783da83491be968e8fe789263689c02724e0c691933c52994f5",
                "sha256:33b74d289bd2f5e527beadcaa3f401e0df0a89927c1559c8566c066fa4248ab7",
                "sha256:3799351e2336dc91ea70b034983ee71cf2f9533cdff7c14c90ea126bfd95d65a",
                "sha256:3ce11ee3f23f79dbd06fb3d63e2f6af7b12db1d46932fe7bd8afa259a5996603",
                "sha256:421be9fbf0ffe9ffd7a378aafebbf6f4602d564d34be190fc19a193232fd12b1",
                "sha256:43093fb83d8343aac0b1baa75516da6092f58f41200907ef92448ecab8825135",
                "sha256:46d00d6cfecdde84d40e572d63735ef81423ad31184100411e6e3388d405e247",
                "sha256:4a33dea2b688b3190ee12bd7cfa29d39c9ed176bda40bfa11099a3ce5d3a7ac6",
                "sha256:4b9fe39a2ccc108a4accc2676e77da025ce383c108593d65cc909add5c3bd601",
                "sha256:56442863ed2b06d19c37f94d999035e15ee982988920e12a5b4ba29b62ad1f77",
                "sha256:671cd1187ed5e62818414afe79ed29da836dde67166a9fac6d435873c44fdd02",
                "sha256:694deca8d702d5db21ec83983ce0bb4b26a578e71fbdbd4fdcd387daa90e4d5e",
                "sha256:6a074d34ee7a5ce3effbc526b7083ec9731bb3cbf921bbe1d3005d4d2bdb3a63",
                "sha256:6d0072fea50feec76a4c418096652f2c3238eaa014b2f94aeb1d56a66b41403f",
                "sha256:6fbf47b5d3728c6aea2abb0589b5d30459e369baa772e0f37a0320185e87c980",
                "sha256:7f91197cc9e48f989d12e4e6fbc46495c446636dfc81b9ccf50bb0ec74b91d4b",
                "sha256:86b1f75c4e7c2ac2ccdaec2b9022845dbb81880ca318bb7a0a01fbf7813e3812",
                "sha256:8dc1c72a69aa7e082593c4a203dcf94ddb74bb5c8a731e4e1eb68d031e8498ff",
                "sha256:8e3dcf21f367459434c18e71b2a9532d96547aef8a871872a5bd69a715c15f96",
                "sha256:8e576a51ad59e4bfaac456023a78f6b5e6e7651dcd383bcc3e18d06f9b55d6d1",
                "sha256:96e37a3dc86e80bf81758c152fe66dbf60ed5eca3d26305edf01892257049925",
                "sha256:97a68e6ada378df82bc9f16b800ab77cbf4b2fada0081794318520138c088e4a",
                "sha256:99a2a507ed3ac881b975a2976d59f38c19386d128e7a9a18b7df6fff1fd4c1d6",
                "sha256:a49907dd8420c5685cfa064a1335b6754b74541bbb3706c259c02ed65b644b3e",
                "sha256:b09bf97215625a311f669476f44b8b318b075847b49316d3e28c08e41a7a573f",
                "sha256:b7bd98b796e2b6553da7225aeb61f447f80a1ca64f41d83612e6139ca5213aa4",
                "sha256:b87db4360013327109564f0e591bd2a3b318547bcef31b468a92ee504d07ae4f",
                "sha256:bcb3ed405ed3222f9904899563d6fc492ff75cce56cba05e32eff40e6acbeaa3",
                "sha256:d4306c36ca495956b6d568d276ac11fdd9c30a36f1b6eb928070dc5360b22e1c",
                "sha256:d5ee4f386140395a2c818d149221149c54849dfcfcb9f1debfe07a8b8bd63f9a",
                "sha256:dda30ba7e87fbbb7eab1ec9f58678558fd9a6b8b853530e176eabd064da81417",
                "sha256:e04e26803c9c3851c931eac40c695602c6295b8d432cbe78609649ad9bd2da8a",
                "sha256:e1c0b87e09fa55a220f058d1d49d3fb8df88fbfab58558f1198e08c1e1de842a",
                "sha256:e72591e9ecd94d7feb70c1cbd7be7b3ebea3f548870aa91e2732960fa4d57a37",
                "sha256:e8c843bbcda3a2f1e3c2ab25913c80a3c5376cd00c6e8c4a86a89a28c8dc5452",
                "sha256:efc1913fd2ca4f334418481c7e595c00aad186563bbc1ec76067848c7ca0a933",
                "sha256:f121a1420d4e173a5d96e47e9a0c0dcff965afdf1626d28de1460815f7c4ee7a",
                "sha256:fc7b548b17d238737688817ab67deebb30e8073c95749d55538ed473130ec0c7"
            ],
            "markers": "python_full_version >= '3.7.0'",
            "version": "==2.1.1"
        },
        "mypy-extensions": {
            "hashes": [
                "sha256:090fedd75945a69ae91ce1303b5824f428daf5a028d2f6ab8a299250a846f15d",
                "sha256:2d82818f5bb3e369420cb3c4060a7970edba416647068eb4c5343488a6c604a8"
            ],
            "version": "==0.4.3"
        },
        "numpy": {
            "hashes": [
                "sha256:092f5e6025813e64ad6d1b52b519165d08c730d099c114a9247c9bb635a2a450",
                "sha256:196cd074c3f97c4121601790955f915187736f9cf458d3ee1f1b46aff2b1ade0",
                "sha256:1c29b44905af288b3919803aceb6ec7fec77406d8b08aaa2e8b9e63d0fe2f160",
                "sha256:2b2da66582f3a69c8ce25ed7921dcd8010d05e59ac8d89d126a299be60421171",
                "sha256:5043bcd71fcc458dfb8a0fc5509bbc979da0131b9d08e3d5f50fb0bbb36f169a",
                "sha256:58bfd40eb478f54ff7a5710dd61c8097e169bc36cc68333d00a9bcd8def53b38",
                "sha256:79a506cacf2be3a74ead5467aee97b81fca00c9c4c8b3ba16dbab488cd99ba10",
                "sha256:94b170b4fa0168cd6be4becf37cb5b127bd12a795123984385b8cd4aca9857e5",
                "sha256:97a76604d9b0e79f59baeca16593c711fddb44936e40310f78bfef79ee9a835f",
                "sha256:98e8e0d8d69ff4d3fa63e6c61e8cfe2d03c29b16b58dbef1f9baa175bbed7860",
                "sha256:ac86f407873b952679f5f9e6c0612687e51547af0e14ddea1eedfcb22466babd",
                "sha256:ae8adff4172692ce56233db04b7ce5792186f179c415c37d539c25de7298d25d",
                "sha256:bd3fa4fe2e38533d5336e1272fc4e765cabbbde144309ccee8675509d5cd7b05",
                "sha256:d0d2094e8f4d760500394d77b383a1b06d3663e8892cdf5df3c592f55f3bff66",
                "sha256:d54b3b828d618a19779a84c3ad952e96e2c2311b16384e973e671aa5be1f6187",
                "sha256:d6ca8dabe696c2785d0c8c9b0d8a9b6e5fdbe4f922bde70d57fa1a2848134f95",
                "sha256:d8cc87bed09de55477dba9da370c1679bd534df9baa171dd01accbb09687dac3",
                "sha256:f0f18804df7370571fb65db9b98bf1378172bd4e962482b857e612d1fec0f53e",
                "sha256:f1d88ef79e0a7fa631bb2c3dda1ea46b32b1fe614e10fedd611d3d5398447f2f",
                "sha256:f9c3fc2adf67762c9fe1849c859942d23f8d3e0bee7b5ed3d4a9c3eeb50a2f07",
                "sha256:fc431493df245f3c627c0c05c2bd134535e7929dbe2e602b80e42bf52ff760bc",
                "sha256:fe8b9683eb26d2c4d5db32cd29b38fdcf8381324ab48313b5b69088e0e355379"
            ],
            "index": "pypi",
            "version": "==1.23.0"
        },
        "pyserde": {
            "hashes": [
                "sha256:344baa54b07e9e05f0068e6e5c584a97dd4f2fc1b411b58c4eebf48f5cb8456e",
                "sha256:9d6789c49e1b8fb628de498ac55c11d615ed2ef77a513b3f24513dd7ef3bc6a3"
            ],
            "index": "pypi",
            "version": "==0.8.2"
        },
        "typing-extensions": {
            "hashes": [
                "sha256:6657594ee297170d19f67d55c05852a874e7eb634f4f753dbd667855e07c1708",
                "sha256:f1c24655a0da0d1b67f07e17a5e6b2a105894e6824b92096378bb3668ef02376"
            ],
            "markers": "python_full_version >= '3.7.0'",
            "version": "==4.2.0"
        },
        "typing-inspect": {
            "hashes": [
                "sha256:047d4097d9b17f46531bf6f014356111a1b6fb821a24fe7ac909853ca2a782aa",
                "sha256:3cd7d4563e997719a710a3bfe7ffb544c6b72069b6812a02e9b414a8fa3aaa6b",
                "sha256:b1f56c0783ef0f25fb064a01be6e5407e54cf4a4bf4f3ba3fe51e0bd6dcea9e5"
            ],
            "version": "==0.7.1"
        }
    },
    "develop": {}
}
```

**Comment by yukinarit** [comment]
Thanks @skogsvik for reporting!
Fixed to use bumpy<1.23.0 for python3.7 and 3.8 in pyserde v0.8.3. 
If you know how to fix the issue, PR is welcome. (Sorry, I am not a numpy user)

**Comment by skogsvik** [comment]
I can't say that I understand what that section of code is attempting to do without digging more into how serde works.

I don't think it is a good idea to rely on private types in someone else's library. They might change something unexpectedly and break your library (such as in this case).

Seeing how this is already a hack, you might chose to double down and simply retry the import if you notice that the class isn't where you expected it....

```diff
diff --git a/serde/compat.py b/serde/compat.py
--- serde/compat.py
+++ serde/compat.py
@@ -16,18 +16,23 @@
     import typing_extensions
 
 try:
     if sys.version_info[:2] <= (3, 8):
-        import numpy.typing as npt
+        # FIXME: Fix this without relying on private types
+        try:
+            from numpy.typing import _generic_alias
+        except ImportError:
+            # As of numpy 1.23.0 the typing library was split into private and public, moving _generic_alias
+            from numpy._typing import _generic_alias
 
         # Note: these functions are only needed on Python 3.8 or earlier
         def get_np_origin(tp):
-            if isinstance(tp, npt._generic_alias._GenericAlias) and tp.__origin__ is not ClassVar:
+            if isinstance(tp, _generic_alias._GenericAlias) and tp.__origin__ is not ClassVar:
                 return tp.__origin__
             return None
 
         def get_np_args(tp):
-            if isinstance(tp, npt._generic_alias._GenericAlias) and tp.__origin__ is not ClassVar:
+            if isinstance(tp, _generic_alias._GenericAlias) and tp.__origin__ is not ClassVar:
                 return tp.__args__
 
             return ()
 
```

**Comment by yukinarit** [comment]
@kmsquire Would you please take a look?
