### ISSUE TITLE
Error when deserializing custom field deserializer with Optional type

### ISSUE THREAD

**Issue by masinc** [yukinarit/pyserde#289]
When using custom field deserializer with `Optional` type, the error will be raised if the key does not exist.

Python: 3.10.8
pyserde: 0.9.5

```python
from dataclasses import dataclass
from typing import Optional
from serde import field, serde, from_dict

@serde
@dataclass
class A:
    a: Optional[int]

@serde
@dataclass
class A2:
    a: Optional[int] = field(deserializer=lambda x: 2)

print(from_dict(A, { 'a': None })) # A(a=None)
print(from_dict(A, { 'a': 1})) # A(a=1)
print(from_dict(A, {})) # A(a=None)
print(from_dict(A2, { 'a': None })) # A2(a=2)
print(from_dict(A2, { 'a': 1 })) # A2(a=2)
print(from_dict(A2, {})) # Error
```

output
```
A(a=None)
A(a=None)
A(a=1)
A2(a=2)
A2(a=2)
Traceback (most recent call last):
  File "/home/masinc/sandbox/a310/.venv/lib/python3.10/site-packages/serde/de.py", line 350, in from_obj
    res = serde_scope.funcs[func_name](c, maybe_generic=maybe_generic, data=o, reuse_instances=reuse_instances)
  File "<string>", line 11, in from_dict
KeyError: 'a'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/masinc/sandbox/a310/main.py", line 20, in <module>
    print(from_dict(A2, {})) # Error
  File "/home/masinc/sandbox/a310/.venv/lib/python3.10/site-packages/serde/de.py", line 426, in from_dict
    return from_obj(cls, o, named=True, reuse_instances=reuse_instances)
  File "/home/masinc/sandbox/a310/.venv/lib/python3.10/site-packages/serde/de.py", line 403, in from_obj
    raise SerdeError(e)
serde.compat.SerdeError: 'a'
```

**Comment by soaxelbrooke** [comment]
Hey @masinc can you test again with the latest version? I wasn't able to repro, and this may have been fixed by a recent change to fix optional unions.

**Comment by masinc** [comment]
Hi @soaxelbrooke
It worked with pyserde 0.9.7. Thanks!
