### ISSUE TITLE
Optional Unions Don't Work?

### ISSUE THREAD

**Issue by soaxelbrooke** [yukinarit/pyserde#293]
See the following minimal example:

```python
from serde import yaml, serde
from dataclasses import dataclass
from typing import Optional, Union

@serde
@dataclass(frozen=True)
class Foo:
    request: Optional[str]

@serde
@dataclass(frozen=True)
class Bar:
    request: Optional[Union[str, int]]


print(yaml.from_yaml(Foo, "{}"))
print(yaml.from_yaml(Bar, "{}"))

```

Expectation is that the second `print` results in `Bar(request=None)`, but instead raises `serde.compat.SerdeError: 'request'`.

Tested on python 3.11.0 and 3.9.7. pyserde version is 0.9.6.

Full stack trace:

```
Foo(request=None)
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/serde/de.py", line 354, in from_obj
    res = serde_scope.funcs[func_name](c, maybe_generic=maybe_generic, data=o, reuse_instances=reuse_instances)
  File "<string>", line 11, in from_dict
KeyError: 'request'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/stuart/tmp/serde-union-fail.py", line 18, in <module>
    print(yaml.from_yaml(Bar, "{}"))
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/serde/yaml.py", line 46, in from_yaml
    return from_dict(c, de.deserialize(s, **opts), reuse_instances=False)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/serde/de.py", line 441, in from_dict
    return from_obj(cls, o, named=True, reuse_instances=reuse_instances)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/serde/de.py", line 418, in from_obj
    raise SerdeError(e)
serde.compat.SerdeError: 'request'
```

**Comment by yukinarit** [comment]
@soaxelbrooke v0.9.7 was published in PyPI, Thanks! 👍

**Comment by soaxelbrooke** [comment]
Thanks for writing such a great package!
