### ISSUE TITLE
Using with `dataclassy`

### ISSUE THREAD

**Issue by robertodr** [yukinarit/pyserde#326]
Hei, thanks for this great library! I'm trying to use it in combination with [`dataclassy`](https://github.com/biqqles/dataclassy).
The following works as I'd expect:
```python
from dataclassy import dataclass

from serde import serde, field
from serde.json import from_json, to_json


@serde
@dataclass(eq=False, slots=True)
class Vehicle:
    wheels: int
    _wheels: int = None #field(default=None, skip=True)

foo = Vehicle(wheels=1)

print(to_json(foo))
```
However, I'd like to skip serializing the internal field. Uncommenting `field(default=None, skip=True)` errors out with:
```python
Traceback (most recent call last):
  File "foo.py", line 27, in <module>
    print(to_json(foo))
  File "/home/roberto/mambaforge/envs/aurora/lib/python3.10/site-packages/serde/json.py", line 65, in to_json
    return se.serialize(to_dict(obj, reuse_instances=False, convert_sets=True), **opts)
  File "/home/roberto/mambaforge/envs/aurora/lib/python3.10/site-packages/serde/json.py", line 45, in serialize
    return json_dumps(obj, **opts)
  File "/home/roberto/mambaforge/envs/aurora/lib/python3.10/site-packages/serde/json.py", line 33, in json_dumps
    return json.dumps(obj, ensure_ascii=ensure_ascii, separators=separators, **opts)
  File "/home/roberto/mambaforge/envs/aurora/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/home/roberto/mambaforge/envs/aurora/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/roberto/mambaforge/envs/aurora/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/roberto/mambaforge/envs/aurora/lib/python3.10/site-packages/serde/numpy.py", line 34, in encode_numpy
    raise TypeError(f"Object of type {fullname(type(obj))} is not serializable")
```

I'm guessing it's because `dataclassy` doesn't have a `field` function, but is there anything I can do to workaround this error?

**Comment by robertodr** [comment]
Thanks for the explanation!
