### ISSUE TITLE
SerdeError deserializing list of optional

### ISSUE THREAD

**Issue by davetapley** [yukinarit/pyserde#329]
Seen on `0.9.7` but then updated and still present on `0.10.2` (#315 is _amazing_ BTW 👏🏻 👏🏻 👏🏻 ):

```py
from dataclasses import dataclass
from serde.json import to_json, from_json

@dataclass
class Foo():
    stuff: list[int | None]

foo = to_json(Foo([1, 2, None]))
from_json(Foo, foo)
```

```
Traceback (most recent call last):
  File "/home/dave/.pyenv/versions/ng/lib/python3.10/site-packages/serde/de.py", line 398, in from_obj
    return deserializable_to_obj(c)
  File "/home/dave/.pyenv/versions/ng/lib/python3.10/site-packages/serde/de.py", line 380, in deserializable_to_obj
    res = serde_scope.funcs[func_name](cls, maybe_generic=maybe_generic, data=o, reuse_instances=reuse_instances)
  File "<string>", line 11, in from_dict
  File "<string>", line 11, in <listcomp>
AttributeError: 'int' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dave/ng/pyserde_list_float_bug.py", line 9, in <module>
    from_json(Foo, foo)
  File "/home/dave/.pyenv/versions/ng/lib/python3.10/site-packages/serde/json.py", line 77, in from_json
    return from_dict(c, de.deserialize(s, **opts), reuse_instances=False)
  File "/home/dave/.pyenv/versions/ng/lib/python3.10/site-packages/serde/de.py", line 486, in from_dict
    return from_obj(cls, o, named=True, reuse_instances=reuse_instances)
  File "/home/dave/.pyenv/versions/ng/lib/python3.10/site-packages/serde/de.py", line 463, in from_obj
    raise SerdeError(e)
serde.compat.SerdeError: 'int' object has no attribute 'get'
```

**Comment by davetapley** [comment]
@yukinarit do you need/want any help on this?

I'll need to implement a workaround soon as I have to ship something, but I'd rather make a PR here if you can point me in the right direction and we can get merged in next week or so 😁

**Comment by yukinarit** [comment]
@davetapley Sorry, I missed this. I will work on this next.

**Comment by davetapley** [comment]
@yukinarit still present in 0.23.0

**Comment by davetapley** [comment]
@yukinarit I did some more 👀 

The `get` in the error is definitely this one:
https://github.com/yukinarit/pyserde/blob/0aedb6fef5c19cb10079c6de041919eaf93bb402/serde/de.py#L880

I don't understand enough to know why it's generated, however as far as I can tell the _only_ test which hits it is:
https://github.com/yukinarit/pyserde/blob/0aedb6fef5c19cb10079c6de041919eaf93bb402/tests/test_union.py#L259

It also looks like these are related:
- https://github.com/JEFuller/pyserde/commit/075949b2ba04ce9ecd01f35e939281fe1dd4e750
- https://github.com/JEFuller/pyserde/commit/2b3b7aef73ec6b7a16f61803be38c0293c7c59ec


Tests:
```py
import logging
from dataclasses import dataclass
from typing import (
    Optional,
    Union,
)


from serde import (
    init as serde_init,
    logger,
    serde,
)
from serde.json import from_json, to_json

logging.basicConfig(level=logging.WARNING)
logger.setLevel(logging.DEBUG)

serde_init(True)


@serde
@dataclass(unsafe_hash=True)
class ListUnionNone:
    """
    List of optionals
    """

    v: list[Union[str, None]]  # noqa

def test_list_union_none() -> None:
    v = ListUnionNone(['a', None, 'b'])
    s = '{"v":["a",null,"b"]}'
    assert s == to_json(v)
    assert v == from_json(ListUnionNone, s)

@serde
@dataclass(unsafe_hash=True)
class ListOptional:
    """
    List of optionals
    """

    v: list[Optional[str]]  # noqa



def test_list_optional() -> None:
    v = ListOptional(['a', None, 'b'])
    s = '{"v":["a",null,"b"]}'
    assert s == to_json(v)
    assert v == from_json(ListUnionNone, s)
```

Both fail with `serde.compat.SerdeError: 'str' object has no attribute 'get'`, as initially reported.

Thanks! 🙏🏻

**Comment by yukinarit** [comment]
This was fixed in https://github.com/yukinarit/pyserde/pull/733
