### ISSUE TITLE
field attributes don't work for derived pyserde class

### ISSUE THREAD

**Issue by solanav** [yukinarit/pyserde#368]
Can I inherit from a class if both use @serde? It doesn't seem to work, serde only finds the fields in the parent class.

Parent class (`dobject.py`):
```python
@serde(rename_all='camelcase')
@dataclass
class Dobject:
    id_: str = field(rename="id")
    metadata: Metadata = field()
    client_metrics_counter: ClientMetricsCounter = field()
    client_names: List[str] = field()
    creation_date: datetime = field(
        serializer=lambda x: to_custom_date(x),
        deserializer=lambda x: from_custom_date(x),
    )
    description: str = field()
    historic: List[History] = field()
    state: str = field()
    tags: List[str] = field()
    type_: str = field(rename="type")
    update_date: datetime = field(
        serializer=lambda x: to_custom_date(x),
        deserializer=lambda x: from_custom_date(x),
    )
    validation_date: datetime = field(
        serializer=lambda x: to_custom_date(x),
        deserializer=lambda x: from_custom_date(x),
    )
    visibility_tags: List[str] = field()
    visible_alias: str = field()
    working_teams: List[str] = field()
```

Son class (`alert.py`):
```python
@serde(rename_all='camelcase')
@dataclass
class Alert(Dobject):
    url: str = field(rename="URL")
    analysis: str = field()
    category: str = field()
    detection_date: datetime = field(
        serializer=lambda x: to_custom_date(x),
        deserializer=lambda x: from_custom_date(x),
    )
    evidences: List = field()
    generated_incidents: int = field()
    incident_state: Optional[str] = field()
    mitre: List = field()
    publication_date: Optional[datetime] = field(
        serializer=lambda x: to_custom_date(x),
        deserializer=lambda x: from_custom_date(x),
    )
    recommendations: Optional[str] = field()
    related_assets: List = field()
    risk_level: str = field()
    summary: str = field()
    title: str = field()
```

Error:
```bash
./test_serde.py::TestSerde::test_alert Failed with Error: 'url'
  File "/home/.../site-packages/serde/de.py", line 408, in from_obj
    return deserializable_to_obj(c)
  File "/home/.../site-packages/serde/de.py", line 388, in deserializable_to_obj
    res = serde_scope.funcs[func_name](cls, maybe_generic=maybe_generic, data=o, reuse_instances=reuse_instances)
  File "<string>", line 41, in from_dict
KeyError: 'url'

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/.../unittest/case.py", line 60, in testPartExecutor
    yield
  File "/home/.../unittest/case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "/home/.../unittest/case.py", line 633, in _callTestMethod
    method()
  File "/home/solanav/Projects/<MY_PROJECT>/tests/test_serde.py", line 106, in test_alert
    alert = from_json(
  File "/home/.../serde/json.py", line 77, in from_json
    return from_dict(c, de.deserialize(s, **opts), reuse_instances=False)
  File "/home/.../serde/de.py", line 494, in from_dict
    return from_obj(cls, o, named=True, reuse_instances=reuse_instances)
  File "/home/.../serde/de.py", line 471, in from_obj
    raise SerdeError(e)
serde.compat.SerdeError: 'url'
```

**Comment by yukinarit** [comment]
Hi @solanav!

Although I didn't test inheritance cases enough, I thought inheritance works as expected. But I found field attributes don't work for inherited class for some reason. 

a. Here is a simple inheritance example without field attributes. It works as expected
```python
from dataclasses import dataclass

from serde import serde, field
from serde.json import from_json, to_json

@serde
@dataclass
class Foo:
    a: int

@serde
@dataclass
class Bar(Foo):
    b: int

def main() -> None:
    f = Bar(1, 2)
    print(f"Into Json: {to_json(f)}")

    s = '{"a": 1, "b": "2"}'
    print(f"From Json: {from_json(Bar, s)}")
```

We get 
```
Into Json: {"a":1,"b":2}
From Json: Bar(a=1, b='2')
```

b. If we add a field attribute `rename` to both base and derived class
```python
from dataclasses import dataclass
from serde import serde, field
from serde.json import from_json, to_json

@serde
@dataclass
class Foo:
    a: int = field(rename="aa")

@serde
@dataclass
class Bar(Foo):
    b: int = field(rename="bb")


def main() -> None:
    f = Bar(1, 2)
    print(f"Into Json: {to_json(f)}")
```

We get this although I expected `{"aa":1,"bb":2}`
```
Into Json: {"aa":1,"b":2}
```

**Comment by yukinarit** [comment]
@solanav 
A workaround is using flatten.

```python
from dataclasses import dataclass

from serde import serde, field
from serde.json import from_json, to_json


@serde
@dataclass
class Foo:
    a: int = field(rename="aa")


@serde
@dataclass
class Bar:
    f: Foo = field(flatten=True)
    b: int = field(rename="bb")


def main() -> None:
    f = Bar(Foo(1), 2)
    print(f"Into Json: {to_json(f)}")

    s = '{"aa": 1, "bb": "2"}'
    print(f"From Json: {from_json(Bar, s)}")

main()
```

We get the expected result
```
Into Json: {"aa":1,"bb":2}
From Json: Bar(f=Foo(a=1), b='2')
```

**Comment by solanav** [comment]
Thanks for the help! I'll use the flatten workaround for now. And congrats on this amazing project to you and all the other collaborators!
