### ISSUE TITLE
InitVar causes exception

### ISSUE THREAD

**Issue by morrison12** [yukinarit/pyserde#425]
I might be misunderstanding the intended use but when I trial to serialise a `dataclass` containing an `InitVar` (e.g. as in the example below) I get this exception:
```python
Traceback (most recent call last):
  File ".../examples/ts2.py", line 10, in <module>
    class Foo:
  File ".../lib/python3.10/site-packages/serde/__init__.py", line 180, in serde
    return wrap(_cls)
  File ".../lib/python3.10/site-packages/serde/__init__.py", line 151, in wrap
    if should_impl_dataclass(cls):
  File ".../lib/python3.10/site-packages/serde/core.py", line 888, in should_impl_dataclass
    field_names = [field.name for field in dataclass_fields(cls)]
  File ".../lib/python3.10/site-packages/serde/compat.py", line 331, in dataclass_fields
    raise SerdeError(
serde.compat.SerdeError: Failed to resolve type hints for Foo:
TypeError: Forward references must evaluate to types. Got dataclasses.InitVar[str].

```
rather than output like:
`{"a":1,"b":{"x":"one", "z":"three"},"c":"end"}`

```python
from __future__ import annotations
from dataclasses import dataclass, InitVar
from serde import serde
from serde.json import to_json

@serde
@dataclass
class Foo:
    x: str
    y: InitVar[str]
    z: str

    def __post_init__(self, y: str):
        self.z = self.y

@serde
@dataclass
class Bar:
    a: int
    b: Foo
    c: float

print(to_json(Bar(1, Foo("one", "two", "three"), 2.25)))

# with Python 3.10.2 and pyserde==0.12.2 gives
# but would have expect
# {"a":1,"b":{"x":"one", "z":"three"},"c":"end"}
```

with `python 3.10.2` and `pyserde==0.12.2`

**Comment by yukinarit** [comment]
Hi @morrison12!

Sorry for the delay, it seems there is an issue of `InitVar` with `from __future__ import annotations`. Let me look into it.

**Comment by yukinarit** [comment]
It's very interesting 

just adding this line resolved the issue!

```python
InitVar.__call__ = lambda *args: None
```

Running this example, produces this output 
```python
from __future__ import annotations
from dataclasses import dataclass, InitVar
from serde import serde
from serde.json import to_json

InitVar.__call__ = lambda *args: None

@serde
@dataclass
class Foo:
    x: str
    y: InitVar[str]
    z: str

    def __post_init__(self, y: str):
        self.z = y

@serde
@dataclass
class Bar:
    a: int
    b: Foo
    c: float

print(to_json(Bar(1, Foo("one", "two", "three"), 2.25)))
```

```
$ python 425.py
{"a":1,"b":{"x":"one","z":"two"},"c":2.25}
```

This behaviour is very well explained [this stackoverflow post](https://stackoverflow.com/a/70430449). For now, please use this workaround. I will try to see if we can have this workaround inside pyserde.

**Comment by morrison12** [comment]
Thanks.. The workaround worked like a charm.
