### ISSUE TITLE
Serialization error for Union with a dataclass arg

### ISSUE THREAD

**Issue by kykosic** [yukinarit/pyserde#427]
Given the following nested setup:
```python
from dataclasses import dataclass

from serde import serde, to_dict


@serde
@dataclass
class Bar:
    num: float = 20


@serde
@dataclass
class Foo:
    b: Bar | int


f = Foo(Bar())

print(to_dict(f))
```
I get this error:
```
Traceback (most recent call last):
  File "pyserde/issue.py", line 20, in <module>
    print(to_dict(f))
  File "pyserde/serde/se.py", line 451, in to_dict
    return to_obj(  # type: ignore
  File "pyserde/serde/se.py", line 379, in to_obj
    raise SerdeError(e) from None
serde.compat.SerdeError: Can not serialize Bar(num=20) of type Bar for Union[Bar, int]
```

Looking at the auto-generated code, it appears [this if statement](https://github.com/yukinarit/pyserde/blob/89680ed429401d41e2a4584b8023cb6366786e41/serde/se.py#L591) resolves to `False`. However, if you replace
```python
  if is_instance(obj, union_args[{{loop.index0}}]):
```
with
```python
  if type(obj) is union_args[{{loop.index0}}]:
```
Then everything works. Haven't had a chance to dig too deep into what the cause of this could be yet.

Seeing this issue on latest pypi release and `main`, Python 3.10.12, tested on MacOS and Linux.

**Comment by yukinarit** [comment]
@kykosic 
If you replace `num: float = 20` with `num: float = 20.0`, it works.

**Comment by yukinarit** [comment]
@kykosic 
Unfortunately there is not documentation that explain this precisely. I will do it when I have time.

**Comment by davetapley** [comment]
I just ran in to this trying to use `serde` to parse incoming JSON where the type is definitely a `float`, but one value was `0`.

Using `serde(type_check=coerce)` will fix it 🚀
