### ISSUE TITLE
`field(skip=True)` doesn't work as expected at version 0.21.0 and above

### ISSUE THREAD

**Issue by huangboming** [yukinarit/pyserde#608]
## Example

```python
from serde import field, serde
from serde.json import to_json


class A:
    x: int
    y: str

    def __init__(self, x: int, y: str):
        self.x = x
        self.y = y


@serde
class B:
    a: int
    b: str
    c: A = field(default=A(x=1, y="2"), skip=True)


if __name__ == "__main__":
    t = B(a=1, b="2")
    print(to_json(t))
```

Here's what I expect:

```shell
> python test.py               
{"a":1,"b":"2"}
```

## Output

At version 0.21.0 and above(I've tested 0.21.0 and 0.22.0), the script throws an exception:

```shell
> python test.py 
Traceback (most recent call last):
  File "/Users/bmh/Documents/tests/test.py", line 23, in <module>
    print(to_json(t))
          ^^^^^^^^^^
  File "/Users/bmh/Library/Caches/pypoetry/virtualenvs/tests-Ey8OvmbW-py3.11/lib/python3.11/site-packages/serde/json.py", line 79, in to_json
    to_dict(obj, c=cls, reuse_instances=reuse_instances, convert_sets=convert_sets), **opts
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bmh/Library/Caches/pypoetry/virtualenvs/tests-Ey8OvmbW-py3.11/lib/python3.11/site-packages/serde/se.py", line 490, in to_dict
    return to_obj(  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bmh/Library/Caches/pypoetry/virtualenvs/tests-Ey8OvmbW-py3.11/lib/python3.11/site-packages/serde/se.py", line 395, in to_obj
    raise SerdeError(e) from None
serde.compat.SerdeError: Unsupported type: A
```

Version info:
```shell
> python -V     
Python 3.11.10

> pip list | grep pyserde
pyserde             0.21.0
```

At version 0.20.0 and below(I've tested 0.15.0, 0.19.0 and 0.20.0), It works as expected:

```shell
> python test.py               
{"a":1,"b":"2"}
```

Version info:
```
> python -V     
Python 3.11.10

> pip list | grep pyserde
pyserde             0.20.0
```

## Env Info

Machine: Macbook pro M2
OS: Sequoia 15.1

**Comment by yukinarit** [comment]
Hi @huangboming! Thanks for using pyserde!

I don't know why that code was supported until v0.20.1. :thinking: 

But your code has a potential bug regarding dataclass's `default` parameter.
If you run the following code, 2nd `print(t2.c.x)` prints 1000000 instead of 1.

```python
if __name__ == "__main__":
    t = B(a=1, b="2")
    # prints 1 Indentation contains tabs
    print(t.c.x)

    t.c.x = 1000000

    t2 = B(a=1, b="2")
    # prints 1000000
    print(t2.c.x)
```

This is more robust code to achieve the same thing, and pyserde works as expected in this way.

```python
from serde import field, serde
from serde.json import to_json


@serde
class A:
    x: int
    y: str


@serde
class B:
    a: int
    b: str
    c: A = field(default_factory=lambda: A(x=1, y="2"), skip=True)


if __name__ == "__main__":
    t = B(a=1, b="2")
    # prints 1
    print(t.c.x)
    print(to_json(t))

    t.c.x = 1000000

    t2 = B(a=1, b="2")
    # prints 1
    print(t2.c.x)
    print(to_json(t2))

```

**Comment by huangboming** [comment]
@yukinarit 

Thank you for quick reply! Really appreciate it. 😊

I didn't realize that for mutable default value, I should use `default_factory` instead of `default`. And after adding `serde` decorator to class A, `skip=True` works as expected 👍

**Comment by yukinarit** [comment]
Good to hear that it worked well! :slightly_smiling_face: 
Let me close this issue.
