### ISSUE TITLE
render tuple does not properly escape quotes when using coerce

### ISSUE THREAD

**Issue by kmsquire** [yukinarit/pyserde#619]
The following code throws a `SyntaxError`:

```python
import serde

@serde.serde(type_check=serde.coerce)
class Foo:
    loc: tuple[float, float]

foo = Foo(loc=(1, 2))
print(serde.to_dict(foo))
```

The error is
```
Traceback (most recent call last):
  File "/Users/kevin.squire/tmp/pyserde/tmp/test2.py", line 5, in <module>
    class Foo:
  File "/Users/kevin.squire/tmp/pyserde/serde/__init__.py", line 182, in wrap
    deserialize(
  File "/Users/kevin.squire/tmp/pyserde/serde/de.py", line 356, in deserialize
    return wrap(_cls)
  File "/Users/kevin.squire/tmp/pyserde/serde/de.py", line 329, in wrap
    add_func(
  File "/Users/kevin.squire/tmp/pyserde/serde/core.py", line 339, in add_func
    code = gen(func_code, globals)
  File "/Users/kevin.squire/tmp/pyserde/serde/core.py", line 325, in gen
    exec(code, globals, locals)
  File "<string>", line 12
    __loc = (coerce_object("Foo", "data["loc"][0]", float, data["loc"][0]), coerce_object("Foo", "data["loc"][1]", float, data["loc"][1]),)
                                  ^^^^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
```

The quotes around `"loc"` need to be escaped in the string in the second argument to `coerce_object`.

Fix forthcoming.

**Comment by kmsquire** [comment]
Also note that the error is not visible if a single character is used instead of `"loc"`, because single quotes are used in that case.

```
import serde

@serde.serde(type_check=serde.coerce)
class Foo:
    f: tuple[float, float]

foo = Foo(f=(1, 2))
print(serde.to_dict(foo))
```
works fine:
```
{'f': (1.0, 2.0)}
```
From `python -m serde.inspect test2.py Foo`, it's really not clear why this is the case, as it still looks wrong:
```python
  __f = (coerce_object("Foo", "data["f"][0]", float, data["f"][0]), coerce_object("Foo", "data["f"][1]", float, data["f"][1]),)
```
