### ISSUE TITLE
Clearer errors when using unsupported types

### ISSUE THREAD

**Issue by nikvaessen** [yukinarit/pyserde#79]
Minimal example:

```python
from dataclasses import dataclass
from typing import Set

from serde import deserialize, serialize


@deserialize
@serialize
@dataclass
class Foo:
    a: Set

```

Gives error:

```
Traceback (most recent call last):
  File "/home/nik/PycharmProjects/pythonProject/main.py", line 10, in <module>
    class Foo:
  File "/home/nik/.cache/pypoetry/virtualenvs/pythonproject-iTa_5C8b-py3.8/lib/python3.8/site-packages/serde/de.py", line 104, in deserialize
    return wrap(_cls)
  File "/home/nik/.cache/pypoetry/virtualenvs/pythonproject-iTa_5C8b-py3.8/lib/python3.8/site-packages/serde/de.py", line 85, in wrap
    getattr(cls, '__serde_scope__')[typ.__name__] = typ
  File "/usr/lib/python3.8/typing.py", line 760, in __getattr__
    raise AttributeError(attr)
AttributeError: __name__
```

Suggestion in `de.py`:

```python3
for typ in iter_types(cls):
    try:
        if is_dataclass(typ) or is_enum(typ) or not is_primitive(typ):
            getattr(cls, '__serde_scope__')[typ.__name__] = typ
    except AttributeError as e:
        raise AttributeError(f"the type {typ} in used on a variable in"
                             f" class {cls.__name__} is not supported. "
                             f"See https://github.com/yukinarit/pyserde#supported-types")

```

would raise

```
Traceback (most recent call last):
  File "/home/nik/.cache/pypoetry/virtualenvs/pythonproject-iTa_5C8b-py3.8/lib/python3.8/site-packages/serde/de.py", line 86, in wrap
    getattr(cls, '__serde_scope__')[typ.__name__] = typ
  File "/usr/lib/python3.8/typing.py", line 760, in __getattr__
    raise AttributeError(attr)
AttributeError: __name__

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nik/PycharmProjects/pythonProject/main.py", line 10, in <module>
    class Foo:
  File "/home/nik/.cache/pypoetry/virtualenvs/pythonproject-iTa_5C8b-py3.8/lib/python3.8/site-packages/serde/de.py", line 109, in deserialize
    return wrap(_cls)
  File "/home/nik/.cache/pypoetry/virtualenvs/pythonproject-iTa_5C8b-py3.8/lib/python3.8/site-packages/serde/de.py", line 88, in wrap
    raise AttributeError(f"the type {typ} in used on a variable in"
AttributeError: the type typing.Set in used on a variable in class Foo is not supported. See https://github.com/yukinarit/pyserde#supported-types
```

**Comment by yukinarit** [comment]
Hi @nikvaessen 

That is nice! Could you please create a MR? I will merge :slightly

**Comment by yukinarit** [comment]
@nikvaessen  
Fixed in https://github.com/yukinarit/pyserde/commit/a13edc699611aa256439153cf5bd772309771f66
