### ISSUE TITLE
Support more standard collections

### ISSUE THREAD

**Issue by yukinarit** [yukinarit/pyserde#83]
* [x] List
* [x] Tuple
* [x] Dict
* [ ] Any
* [ ] Set
* [ ] FrozenSet
* [ ] DefaultDict
* [ ] OrderedDict
* [ ] ChainMap
* [ ] Counter
* [ ] Deque

**Comment by davetapley** [comment]
@yukinarit one more: [`namedtuple`](https://docs.python.org/3/library/collections.html#collections.namedtuple):

```py
Point = namedtuple('Point', ['x', 'y'])

@dataclass
class Foo:
   p: Point


f = Foo(Point(1,2))
to_json(f)
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/python/3.12.2/lib/python3.12/site-packages/serde/json.py", line 75, in to_json
    to_dict(obj, c=cls, reuse_instances=reuse_instances, convert_sets=convert_sets), **opts
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.2/lib/python3.12/site-packages/serde/se.py", line 458, in to_dict
    return to_obj(  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.2/lib/python3.12/site-packages/serde/se.py", line 386, in to_obj
    raise SerdeError(e) from None
serde.compat.SerdeError: Unsupported type: Point

**Comment by yukinarit** [comment]
@davetapley 
I thought namedtuple is obsolete in favor of dataclass :slightly_smiling_face: 

If you want oneliner to declare, how about using [make_dataclass](https://docs.python.org/3/library/dataclasses.html#dataclasses.make_dataclass)?

**Comment by davetapley** [comment]
@yukinarit I was hoping it could serialize to a tuple, so e.g. in YAML I could write:

```yaml
- [1,2]
- [3,4]
```

instead of:

```yaml
- x: 1
  y: 2
- x: 4
  y: 3

But still have the the `.` accessor once deserialized:

``py
p.x + p.y               # fields also accessible by name
```

**Comment by davetapley** [comment]
@yukinarit good timing: https://discuss.python.org/t/add-iter-true-to-dataclass-decorator/78002/3
